/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "7458.v:1.1-18.10" *)
module top_module(p1a, p1b, p1c, p1d, p1e, p1f, p1y, p2a, p2b, p2c, p2d, p2y);
  (* src = "7458.v:14.4-14.25" *)
  wire _0_;
  (* src = "7458.v:15.4-15.25" *)
  wire _1_;
  (* src = "7458.v:2.11-2.14" *)
  input p1a;
  wire p1a;
  (* src = "7458.v:2.16-2.19" *)
  input p1b;
  wire p1b;
  (* src = "7458.v:2.21-2.24" *)
  input p1c;
  wire p1c;
  (* src = "7458.v:2.26-2.29" *)
  input p1d;
  wire p1d;
  (* src = "7458.v:2.31-2.34" *)
  input p1e;
  wire p1e;
  (* src = "7458.v:2.36-2.39" *)
  input p1f;
  wire p1f;
  (* src = "7458.v:3.12-3.15" *)
  output p1y;
  wire p1y;
  (* src = "7458.v:4.11-4.14" *)
  input p2a;
  wire p2a;
  (* src = "7458.v:4.16-4.19" *)
  input p2b;
  wire p2b;
  (* src = "7458.v:4.21-4.24" *)
  input p2c;
  wire p2c;
  (* src = "7458.v:4.26-4.29" *)
  input p2d;
  wire p2d;
  (* src = "7458.v:5.12-5.15" *)
  output p2y;
  wire p2y;
  (* src = "7458.v:8.6-8.9" *)
  wire pab;
  (* src = "7458.v:8.16-8.20" *)
  wire pabc;
  (* src = "7458.v:8.11-8.14" *)
  wire pcd;
  (* src = "7458.v:8.22-8.26" *)
  wire pdef;
  assign pab = p2a & (* src = "7458.v:10.4-10.19" *) p2b;
  assign pcd = p2c & (* src = "7458.v:11.4-11.19" *) p2d;
  assign _0_ = p1a & (* src = "7458.v:14.4-14.25" *) p1b;
  assign pabc = _0_ & (* src = "7458.v:14.4-14.25" *) p1c;
  assign _1_ = p1d & (* src = "7458.v:15.4-15.25" *) p1e;
  assign pdef = _1_ & (* src = "7458.v:15.4-15.25" *) p1f;
  assign p2y = pab | (* src = "7458.v:12.3-12.18" *) pcd;
  assign p1y = pabc | (* src = "7458.v:16.3-16.20" *) pdef;
endmodule
