/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "decoder3_8.v:1.1-25.10" *)
module decoder_3to8_beh(En, A, B, C, Y);
  (* src = "decoder3_8.v:5.2-24.5" *)
  wire [7:0] _0_;
  (* src = "decoder3_8.v:2.11-2.12" *)
  input A;
  wire A;
  (* src = "decoder3_8.v:2.13-2.14" *)
  input B;
  wire B;
  (* src = "decoder3_8.v:2.15-2.16" *)
  input C;
  wire C;
  (* src = "decoder3_8.v:2.8-2.10" *)
  input En;
  wire En;
  (* src = "decoder3_8.v:3.19-3.20" *)
  output [7:0] Y;
  wire [7:0] Y;
  (* full_case = 32'd1 *)
  (* src = "decoder3_8.v:12.2-22.9" *)
  reg [7:0] _1_ [7:0];
  initial begin
    _1_[0] = 8'h01;
    _1_[1] = 8'h02;
    _1_[2] = 8'h04;
    _1_[3] = 8'h08;
    _1_[4] = 8'h10;
    _1_[5] = 8'h20;
    _1_[6] = 8'h40;
    _1_[7] = 8'h80;
  end
  assign _0_ = _1_[{ A, B, C }];
  assign Y = En ? (* full_case = 32'd1 *) (* src = "decoder3_8.v:7.6-7.16|decoder3_8.v:7.2-23.5" *) _0_ : 8'h00;
endmodule
